const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    category: "beach",
    description:
      "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    category: "city",
    description:
      "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    category: "mountain",
    description:
      "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    category: "heritage",
    description:
      "Experience the charm of Tuscany in this beautifully restored villa.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    category: "forest",
    description: "Live among the treetops in this unique treehouse retreat.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    },
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    category: "beach",
    description:
      "Step out of your door onto the sandy beach. Ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Rustic Cabin by the Lake",
    category: "camping",
    description: "Spend your days fishing and kayaking on the serene lake.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Penthouse with City Views",
    category: "city",
    description: "Indulge in luxury living with panoramic city views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    category: "mountain",
    description: "Hit the slopes right from your doorstep.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge in the Serengeti",
    category: "forest",
    description: "Experience the thrill of the wild up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
  },
  {
    title: "Historic Canal House",
    category: "heritage",
    description: "Stay in a beautifully preserved canal house.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
  },
  {
    title: "Private Island Retreat",
    category: "trending",
    description: "Have an entire island to yourself.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
  },

  /* ===== FIXED CASTLE IMAGES ===== */

  {
    title: "Historic Castle in Scotland",
    category: "castle",
    description: "Live like royalty in a historic castle.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98",
    },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
  },
  {
    title: "Ancient Castle Stay in Europe",
    category: "castle",
    description:
      "Stay inside a medieval castle surrounded by history and legends.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383",
    },
    price: 4200,
    location: "Bavaria",
    country: "Germany",
  },
  {
    title: "French Countryside Castle",
    category: "castle",
    description: "Stay in a historic countryside castle.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455",
    },
    price: 3800,
    location: "Loire Valley",
    country: "France",
  },

  /* ===== FIXED ROOM IMAGES ===== */

  {
    title: "Minimal Private Room",
    category: "rooms",
    description: "Clean private room for solo travelers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 500,
    location: "Pune",
    country: "India",
  },
  {
    title: "City Budget Room Near Metro",
    category: "rooms",
    description:
      "Affordable private room near metro station, ideal for solo travelers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c",
    },
    price: 600,
    location: "Delhi",
    country: "India",
  },

  /* ===== REST UNCHANGED ===== */

  {
    title: "Royal Palace Stay",
    category: "heritage",
    description:
      "Experience royal living in a restored palace with traditional architecture.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da",
    },
    price: 2800,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Luxury Pool Villa in Udaipur",
    category: "pool",
    description:
      "Private luxury villa with infinity pool overlooking the Aravalli hills.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
    },
    price: 3200,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Hilltop Camping Experience",
    category: "camping",
    description:
      "Pitch your tent on a hilltop and enjoy sunrise views and bonfire nights.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
    },
    price: 500,
    location: "Bir Billing",
    country: "India",
  },
  {
    title: "Beach Hut in Andaman",
    category: "beach",
    description:
      "Wooden beach hut just steps away from crystal-clear blue waters.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 1400,
    location: "Havelock Island",
    country: "India",
  },
  {
    title: "Snowy Mountain Cabin",
    category: "mountain",
    description: "Cabin surrounded by snow-covered peaks.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1549880338-65ddcdfd017b",
    },
    price: 1400,
    location: "Manali",
    country: "India",
  },
  {
    title: "Alpine Lodge Stay",
    category: "mountain",
    description: "Traditional alpine lodge experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    },
    price: 2800,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Hilltop Wooden Cabin",
    category: "mountain",
    description: "Wooden cabin with valley views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    },
    price: 1200,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Remote Mountain Hut",
    category: "mountain",
    description: "Remote hut for adventure seekers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    },
    price: 900,
    location: "Patagonia",
    country: "Argentina",
  },
  {
    title: "Downtown City Apartment",
    category: "city",
    description: "Apartment in the city center.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 1900,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Modern City Highrise",
    category: "city",
    description: "Highrise apartment with skyline views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
    },
    price: 2200,
    location: "Hong Kong",
    country: "China",
  },
  {
    title: "City Studio Flat",
    category: "city",
    description: "Compact studio flat for urban living.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    },
    price: 1700,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Luxury City Penthouse",
    category: "city",
    description: "Premium penthouse in city core.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    },
    price: 3800,
    location: "New York",
    country: "United States",
  },
  {
    title: "Downtown City Apartment",
    category: "city",
    description: "Apartment in the city center.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 1900,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Modern City Highrise",
    category: "city",
    description: "Highrise apartment with skyline views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
    },
    price: 2200,
    location: "Hong Kong",
    country: "China",
  },
  {
    title: "City Studio Flat",
    category: "city",
    description: "Compact studio flat for urban living.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    },
    price: 1700,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Luxury City Penthouse",
    category: "city",
    description: "Premium penthouse in city core.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    },
    price: 3800,
    location: "New York",
    country: "United States",
  },
  {
    title: "Budget Private Room",
    category: "rooms",
    description: "Affordable private room for short stays.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 450,
    location: "Kolkata",
    country: "India",
  },
  {
    title: "Cozy Room Near IT Park",
    category: "rooms",
    description: "Ideal room for working professionals.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0",
    },
    price: 650,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Shared Hostel Room",
    category: "rooms",
    description: "Backpacker-friendly shared room.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c",
    },
    price: 300,
    location: "Bangkok",
    country: "Thailand",
  },
  {
    title: "Minimal Guest Room",
    category: "rooms",
    description: "Minimal and clean guest room.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    },
    price: 550,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Trending City Studio",
    category: "trending",
    description: "Most booked city studio this month.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    },
    price: 2100,
    location: "Dubai",
    country: "United Arab Emirates",
  },
  {
    title: "Trending Beach Condo",
    category: "trending",
    description: "Loved beachfront condo with sea views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    },
    price: 2200,
    location: "Goa",
    country: "India",
  },
  {
    title: "Trending Mountain Chalet",
    category: "trending",
    description: "Highly rated mountain chalet.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    },
    price: 2600,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Trending Luxury Villa",
    category: "trending",
    description: "Luxury villa trending among couples.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
    },
    price: 3500,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Forest Camping Experience",
    category: "camping",
    description: "Camping tents inside dense forest.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
    },
    price: 450,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Lakeside Camping",
    category: "camping",
    description: "Camping beside a calm lake.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1508873699372-7aeab60b44c6",
    },
    price: 550,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Mountain Tent Stay",
    category: "camping",
    description: "Tent stay with mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
    },
    price: 500,
    location: "Kasol",
    country: "India",
  },
  {
    title: "Desert Camping Night",
    category: "camping",
    description: "Desert camping with bonfire and stars.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 600,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Organic Farm Stay",
    category: "farm",
    description: "Organic farm stay with fresh local food.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1590080877777-6be3e29fa70b",
    },
    price: 650,
    location: "Nashik",
    country: "India",
  },
  {
    title: "Countryside Farmhouse",
    category: "farm",
    description: "Relaxing farmhouse surrounded by fields.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    },
    price: 800,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Village Farm Cottage",
    category: "farm",
    description: "Peaceful village farm cottage.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455",
    },
    price: 700,
    location: "Punjab",
    country: "India",
  },
  {
    title: "Mountain Farm Retreat",
    category: "farm",
    description: "Farm stay surrounded by mountains.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    },
    price: 900,
    location: "Himachal Pradesh",
    country: "India",
  },
  {
    title: "Glass Igloo Stay",
    category: "arctic",
    description: "Glass igloo under northern lights.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    },
    price: 4800,
    location: "Lapland",
    country: "Finland",
  },
  {
    title: "Snow Lodge Experience",
    category: "arctic",
    description: "Stay inside a snow lodge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
    },
    price: 5200,
    location: "Tromsø",
    country: "Norway",
  },
  {
    title: "Frozen Lake Cabin",
    category: "arctic",
    description: "Cabin beside a frozen lake.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519817650390-64a93db511aa",
    },
    price: 4600,
    location: "Yukon",
    country: "Canada",
  },
  {
    title: "Arctic Wilderness Hut",
    category: "arctic",
    description: "Remote hut in arctic wilderness.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    },
    price: 5000,
    location: "Svalbard",
    country: "Norway",
  },
  {
    title: "Forest Cabin Escape",
    category: "forest",
    description: "Wooden cabin deep inside forest.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    },
    price: 950,
    location: "Black Forest",
    country: "Germany",
  },
  {
    title: "Rainforest Tree House",
    category: "forest",
    description: "Tree house inside rainforest.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9",
    },
    price: 1100,
    location: "Amazon",
    country: "Brazil",
  },
  {
    title: "Jungle Eco Retreat",
    category: "forest",
    description: "Eco retreat inside jungle.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    },
    price: 900,
    location: "Kerala",
    country: "India",
  },
  {
    title: "Forest View Lodge",
    category: "forest",
    description: "Lodge with panoramic forest views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e",
    },
    price: 1300,
    location: "Oregon",
    country: "United States",
  },
  {
    title: "Ancient Haveli Stay",
    category: "heritage",
    description: "Traditional haveli with royal interiors.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98",
    },
    price: 2600,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Colonial Heritage Home",
    category: "heritage",
    description: "Colonial-era heritage bungalow.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f",
    },
    price: 2100,
    location: "Pondicherry",
    country: "India",
  },
  {
    title: "Historic Townhouse",
    category: "heritage",
    description: "Restored historic townhouse.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4",
    },
    price: 1900,
    location: "Prague",
    country: "Czech Republic",
  },
  {
    title: "Royal Heritage Palace",
    category: "heritage",
    description: "Palace converted into heritage hotel.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da",
    },
    price: 3000,
    location: "Jaipur",
    country: "India",
  },
];

module.exports = { data: sampleListings };
